# Generated by Django 4.0.2 on 2022-03-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bithday',
            field=models.DateField(null=True),
        ),
    ]
