# Generated by Django 4.0.2 on 2022-03-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_usuario_bithday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='bithday',
            new_name='birthday',
        ),
    ]
