# Generated by Django 4.0.2 on 2022-03-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0007_regalo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='descripcion',
            field=models.CharField(default='vacio', max_length=30),
        ),
    ]
