# Generated by Django 4.0.2 on 2022-03-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0008_regalo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
