# Generated by Django 4.0.2 on 2022-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('Genero', models.CharField(choices=[('SH', 'Hombre'), ('SM', 'Mujer'), ('NB', 'No binario'), ('NA', 'Indefinido')], default='NA', max_length=2)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=72)),
                ('bithday', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
