# Generated by Django 4.0.2 on 2022-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
