# Generated by Django 4.0.2 on 2022-02-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='cantidad_habitantes',
            field=models.IntegerField(default=1),
        ),
    ]
