# Generated by Django 4.0.2 on 2022-02-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dojos_ninjas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ninja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='app.dojos')),
            ],
        ),
        migrations.DeleteModel(
            name='ninjas',
        ),
    ]
