# Generated by Django 4.0.2 on 2022-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ninja_delete_ninjas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='descr',
            field=models.CharField(default='undetermined', max_length=255),
            preserve_default=False,
        ),
    ]
