# Generated by Django 4.0.2 on 2022-02-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='undefined'),
            preserve_default=False,
        ),
    ]
