# Generated by Django 4.0.2 on 2022-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=72)),
                ('birthday', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
