# Generated by Django 3.2.9 on 2021-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deseos2', '0003_alter_user1_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
